config/routes.rb
Rails.application.routes.draw do
  
  root 'chat_rooms#index' 
 
  resources :chat_rooms do
    member do
      post '/join' => 'chat_rooms#user_admit_room', as: 'join'
    end
  end
  devise_for :users
  
  
  
  
end

app/models/admission.rb
class Admission < ApplicationRecord
    belongs_to :user
    belongs_to :chat_room, counter_cache: true
    
    after_commit :user_join_chat_room_notification, on: :create
    
    def user_join_chat_room_notification
        Pusher.trigger('chat_room', 'join', { chat_room_id: self.chat_room_id, email: self.user.email }.as_json)
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
    belongs_to :user
    belongs_to :chat_room
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
    has_many :admissions
    has_many :users, through: :admissions
    
    has_many :chats
    
    
    after_commit :create_chat_room_notification, on: :create
    # after_commit :master_admit_room, on: :create
    # ChatRoom이 하나 만들어 지고 나면 다음 메소드를 실행한다.
    # on 뒤에는 CRUD만 들어감
    
    def user_admit_room(user) # instance method
        # ChatRoom이 하나 만들어 지고 나면 다음 메소드를 실행한다.
        Admission.create(user_id: user.id, chat_room_id: self.id)
    end
    
    # Pusher.trigger
    
    def create_chat_room_notification
        Pusher.trigger('chat_room', 'create', self.as_json)
        # (channer_name, event_name, data)
        # channer의 이름과, 이 channel에서 발생할 event_name, 그리고 이 event에 전달할 data
    end
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :admissions
  has_many :chat_rooms, through: :admissions
  has_many :chats
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :set_chat_room, only: [:show, :edit, :update, :destroy, :user_admit_room]
  before_action :authenticate_user!, except: [:index]
  # GET /chat_rooms
  # GET /chat_rooms.json
  def index
    @chat_rooms = ChatRoom.all
  end

  # GET /chat_rooms/1
  # GET /chat_rooms/1.json
  def show
  end

  # GET /chat_rooms/new
  def new
    @chat_room = ChatRoom.new
  end

  # GET /chat_rooms/1/edit
  def edit
  end

  # POST /chat_rooms
  # POST /chat_rooms.json
  def create
    @chat_room = ChatRoom.new(chat_room_params)
    @chat_room.master_id = current_user.email
    respond_to do |format|
      if @chat_room.save
        
        @chat_room.user_admit_room(current_user) # Admission create method
        
        format.html { redirect_to @chat_room, notice: 'Chat room was successfully created.' }
        format.json { render :show, status: :created, location: @chat_room }
      else
        format.html { render :new }
        format.json { render json: @chat_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chat_rooms/1
  # PATCH/PUT /chat_rooms/1.json
  def update
    respond_to do |format|
      if @chat_room.update(chat_room_params)
        format.html { redirect_to @chat_room, notice: 'Chat room was successfully updated.' }
        format.json { render :show, status: :ok, location: @chat_room }
      else
        format.html { render :edit }
        format.json { render json: @chat_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chat_rooms/1
  # DELETE /chat_rooms/1.json
  def destroy
    @chat_room.destroy
    respond_to do |format|
      format.html { redirect_to chat_rooms_url, notice: 'Chat room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def user_admit_room #room에 join하는 method
    # 현재 유저가 있는 방에서 join버튼을 눌렀을 때, 동작하는 액션
    @chat_room.user_admit_room(current_user)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat_room
      @chat_room = ChatRoom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chat_room_params
      params.fetch(:chat_room, {}).permit(:title, :max_count)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/views/chat_rooms/_form.html.erb
<%= form_for(chat_room) do |f| %>
  <% if chat_room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chat_room.errors.count, "error") %> prohibited this chat_room from being saved:</h2>

      <ul>
      <% chat_room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  
  <div class="form-group">
    <%= f.label :max_count %>
    <%= f.number_field :max_count %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chat_rooms/edit.html.erb
<h1>Editing Chat Room</h1>

<%= render 'form', chat_room: @chat_room %>

<%= link_to 'Show', @chat_room %> |
<%= link_to 'Back', chat_rooms_path %>

app/views/chat_rooms/index.html.erb
<% if user_signed_in? %>
<%= current_user.email %> / <%= link_to 'log out', destroy_user_session_path, method: "delete" %>
<% else %>
<%= link_to 'log in', new_user_session_path %>
<% end %>


<hr>


<h1>Chat Rooms</h1>

<table>
  <thead>
    <tr>
      <th>방제</th>
      <th>인원</th>
      <th>방장</th>
    </tr>
  </thead>

  <tbody class="chat_room_list">
    <% @chat_rooms.reverse.each do |chat_room| %>
      <tr>
        <td><%= chat_room.title %></td>
        <td><span class="current<%=chat_room.id%>"><%= chat_room.admissions.size %></span>/<%= chat_room.max_count %></td>
        <td><%= chat_room.master_id%></td>
        <td><%= link_to 'Show', chat_room %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chat Room', new_chat_room_path %>

<script>
$(document).on('ready', function(){
  // 방이 만들어졌을 때, 방에 대한 데이터를 받아서 
  // 방 목록에 추가해주는 js function
  function room_created(data) {
    $('.chat_room_list').prepend(`
      <tr>
        <td>${data.title}</td>
        <td><span class="current${data.id}">0</span>/${data.max_count}</td>
        <td>${data.master_id}</td>
        <td><a href= "/chat_rooms/${data.id}">Show</a></td>
      </tr>`);
      // alert("방이 추가됨~");
  }
  
  function user_joined(data){
    var current =  $(`.current${data.chat_room_id}`);
    current.text(parseInt(current.text()) + 1)
  }
  
  // chat_room/ create
  var pusher = new Pusher("<%=ENV["pusher_key"]%>", {
    cluster: "<%= ENV["pusher_cluster"] %>",
    encrypted: true
  });

  var channel = pusher.subscribe('chat_room');
  channel.bind('create', function(data) {
    console.log(data);
    room_created(data);
  });
  
  channel.bind('join', function(data) {
    console.log(data);
    user_joined(data)
  });
  
  
  
});
</script>

app/views/chat_rooms/new.html.erb
<h1>New Chat Room</h1>

<%= render 'form', chat_room: @chat_room %>

<%= link_to 'Back', chat_rooms_path %>

app/views/chat_rooms/show.html.erb
<%= current_user.email %>
<h3>현재 접속한 사람</h3>
<div class="joined_user_list">
<% @chat_room.users.each do |user|%>
<p><%= user.email %></p>
<% end %>
</div>
<hr>
<% unless @chat_room.users.include?(current_user)%>
<%= link_to 'Join', join_chat_room_path(@chat_room), method: "post", class: "join_room", remote: true %> |
<% end %>
<%= link_to 'Edit', edit_chat_room_path(@chat_room) %> |
<%= link_to 'Back', chat_rooms_path %>


<script>
$(document).on('ready', function(){
    
  function user_joined(data) {
      
      $('.joined_user_list').append(`<p>${data.email}</p>`)
      var joinroom = $('.join_room')
      console.log(data.email+"/"+"<%=current_user.email%>")
      
      if(data.email=="<%=current_user.email%>"){
          $('.join_room').remove();
      }
      
  }
    
    
    
    
  var pusher = new Pusher("<%=ENV["pusher_key"]%>", {
    cluster: "<%= ENV["pusher_cluster"] %>",
    encrypted: true
  });

  var channel = pusher.subscribe('chat_room');
  
  channel.bind('join', function(data) {
    console.log(data);
    user_joined(data);
  });
  
  
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>
    <script src="https://js.pusher.com/4.1/pusher.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>